/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-10-24 04:43:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.lmc.member.model.vo.Member;

public final class myPageInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/member/myPage.jsp", Long.valueOf(1698051392000L));
    _jspx_dependants.put("/views/member/../common/menubar.jsp", Long.valueOf(1698080520456L));
    _jspx_dependants.put("/views/member/../common/footer.jsp", Long.valueOf(1697763428000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.lmc.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<!--\r\n");
      out.write("<meta http-equiv=\"Cache-Control\" content=\"max-age=0\" />\r\n");
      out.write("<meta http-equiv=\"Cache-Control\" content=\"no-cache\" />\r\n");
      out.write("<meta http-equiv=\"Expires\" content=\"0\" />\r\n");
      out.write("<meta http-equiv=\"Expires\" content=\"Tue, 01 Jan 1980 1:00:00 GMT\" />\r\n");
      out.write("<meta http-equiv=\"Pragma\" content=\"no-cache\">\r\n");
      out.write("-->\r\n");
      out.write("<meta http-equiv=\"Cache-Control\" content=\"no-cache\" />\r\n");
      out.write("<title>MyPageInfo</title>\r\n");
      out.write("	<style type=\"text/css\">\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		.wrapBody {\r\n");
      out.write("            width: 1200px;\r\n");
      out.write("            height: 800px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("        .wrapBody>div {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        .body { \r\n");
      out.write("            height: 100%; \r\n");
      out.write("        }\r\n");
      out.write("        .body>div {\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            float: left;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        .body_1 { width: 300px; }\r\n");
      out.write("        .body_2 { width: 900px; }\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        .outer {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            border: 1px dotted lightgray;\r\n");
      out.write("            margin-top: 50px;\r\n");
      out.write("        }\r\n");
      out.write("        #mypage-form table { margin: auto; }\r\n");
      out.write("        #mypage-form input { margin: 5px; }\r\n");
      out.write("        #mypage-form button { margin: 5px; }\r\n");
      out.write("	</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   ");
 String contextPath = request.getContextPath();
   
	// 로그인한 회원의 정보를 session 으로부터 뽑아내기
	// session.getAttribute("키값") : Object (밸류값)
	Member loginUser = (Member)session.getAttribute("loginUser");
	// session 에 담아둔 1회성 알람문구를 변수로 담아두기
	String alertMsg = (String)session.getAttribute("alertMsg");
   
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>LMC Menu Bar</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Latest compiled and minified CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- jQuery 라이브러리 연동 (온라인 방식) -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Popper JS -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Latest compiled JavaScript -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- 아이콘 연동 -->\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/53a8c415f1.js\" crossorigin=\"anonymous\"></script> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("    /* 글꼴 */\r\n");
      out.write("    @font-face {\r\n");
      out.write("        font-family: 'KimjungchulGothic';\r\n");
      out.write("        src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2302_01@1.0/KimjungchulGothic-Bold.woff2') format('woff2');\r\n");
      out.write("        font-style: normal;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @font-face {\r\n");
      out.write("        font-family: 'Dokrip';\r\n");
      out.write("        src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_twelve@1.1/Dokrip.woff') format('woff');\r\n");
      out.write("        font-weight: normal;\r\n");
      out.write("        font-style: normal;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @font-face {\r\n");
      out.write("        font-family: 'LINESeedKR-Bd';\r\n");
      out.write("        src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_11-01@1.0/LINESeedKR-Bd.woff2') format('woff2');\r\n");
      out.write("        font-weight: 200;\r\n");
      out.write("        font-style: normal;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @font-face {\r\n");
      out.write("        font-family: 'NanumBarunGothic';\r\n");
      out.write("        font-style: normal;\r\n");
      out.write("        font-weight: 900;\r\n");
      out.write("        src: url('//cdn.jsdelivr.net/font-nanumlight/1.0/NanumBarunGothicWebLight.eot');\r\n");
      out.write("        src: url('//cdn.jsdelivr.net/font-nanumlight/1.0/NanumBarunGothicWebLight.eot?#iefix') format('embedded-opentype'), url('//cdn.jsdelivr.net/font-nanumlight/1.0/NanumBarunGothicWebLight.woff') format('woff'), url('//cdn.jsdelivr.net/font-nanumlight/1.0/NanumBarunGothicWebLight.ttf') format('truetype');\r\n");
      out.write("        }\r\n");
      out.write("    \r\n");
      out.write("    body {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        background-color: #e0e0e0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .wrap {\r\n");
      out.write("        width: 1200px;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .top-bar {\r\n");
      out.write("        background-color: #eeeeee;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-between; /* 간격을 최대로 설정하여 양 끝에 정렬 */\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        padding: 10px 20px;\r\n");
      out.write("        font-family: 'LINESeedKR-Bd'; \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .logo {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .logo img {\r\n");
      out.write("        width: 60px;\r\n");
      out.write("        margin-right: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .logo a {\r\n");
      out.write("        font-family: 'Dokrip';\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: black;\r\n");
      out.write("        font-size: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu {\r\n");
      out.write("        list-style: none;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        display: flex;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu li {\r\n");
      out.write("        margin-right: 50px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu a {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: black;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu a::before {\r\n");
      out.write("        content: \"\";\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 1.3px;\r\n");
      out.write("        bottom: 0;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        background-color: black;\r\n");
      out.write("        transform: scaleX(0); /* 처음에는 밑줄이 안 보이도록 설정 */\r\n");
      out.write("        transition: all 0.3s ease-in-out; /* 애니메이션 적용 */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu a:hover::before {\r\n");
      out.write("        visibility: visible;\r\n");
      out.write("        transform: scaleX(1); /* 호버됐을 때 밑줄 */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .search-box {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        background-color: #cfcfcf;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        padding: 5px 10px;\r\n");
      out.write("        height: 40px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .search-box input[type=\"text\"] {\r\n");
      out.write("        border: none;\r\n");
      out.write("        background-color: transparent; /* 검색 상자 배경 투명 */\r\n");
      out.write("        color: black;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        padding: 5px;\r\n");
      out.write("        outline: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .search-box button {\r\n");
      out.write("        background-color: transparent; /* 검색 아이콘 배경 투명 */\r\n");
      out.write("        border: none;\r\n");
      out.write("        color: #333;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        margin-left: 5px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login {\r\n");
      out.write("        font-size: 11px;\r\n");
      out.write("        margin-right: 15px;\r\n");
      out.write("        color: gray;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: gray;\r\n");
      out.write("        padding: 7px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /*회원가입폼 */\r\n");
      out.write("\r\n");
      out.write("	.outerInsert {\r\n");
      out.write("		width : 1000px;\r\n");
      out.write("		margin : auto;\r\n");
      out.write("		margin-top : 50px;\r\n");
      out.write("		border : 1px dotted lightgray;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#enroll-form table { margin : auto; }\r\n");
      out.write("	#enroll-form input { margin : 5px; \r\n");
      out.write("        border : 1px solid lightgray;\r\n");
      out.write("                         border-radius: 5px;\r\n");
      out.write("                   color: #585858;\r\n");
      out.write("                   margin-left: 30px;       \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #enroll-form #checked1, #enroll-form #checked2{\r\n");
      out.write("\r\n");
      out.write("        margin-left: 200px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #user table{\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    #user b{\r\n");
      out.write("        color : rgb(255, 123, 0)\r\n");
      out.write("    }\r\n");
      out.write("    #user button{\r\n");
      out.write("        width: 100px;\r\n");
      out.write("        height : 45px;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        border : 1px solid lightgray;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    #user hr{\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #user hr{\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("    }\r\n");
      out.write("  \r\n");
      out.write("    .modal-body input {\r\n");
      out.write("        background-color: rgb(240, 239, 239);\r\n");
      out.write("        border-style : none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #login{\r\n");
      out.write("        float:left;\r\n");
      out.write("    }\r\n");
      out.write("  \r\n");
      out.write("    #footerLogin>button{\r\n");
      out.write("        width: 40%;\r\n");
      out.write("        height: 50px;\r\n");
      out.write("        border-radius: 25px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("		// script 태그 내에서도 스크립틀릿과 같은 jsp 요소들 사용 가능!!\r\n");
      out.write("		\r\n");
      out.write("		let msg = \"");
      out.print( alertMsg );
      out.write("\";\r\n");
      out.write("		// \"null\" / \"성공적으로 로그인이 되었습니다.\"\r\n");
      out.write("		\r\n");
      out.write("		if(msg != \"null\") {\r\n");
      out.write("			\r\n");
      out.write("			alert(msg);\r\n");
      out.write("			// 알람창을 띄워준 후 session 에 담긴 해당 메세지는\r\n");
      out.write("			// 항상 지워줘야 함!!\r\n");
      out.write("			// => 안그러면 menubar.jsp 가 로딩될때마다\r\n");
      out.write("			//	  매번 alert 가 뜨기 때문\r\n");
      out.write("			\r\n");
      out.write("			");

				session.removeAttribute("alertMsg");
			
      out.write("\r\n");
      out.write("		}	\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("        <div class=\"top-bar\">\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/images/Logo.png\" alt=\"로고\">LMC</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul class=\"menu\">\r\n");
      out.write("                <li><a href=\"");
      out.print( contextPath );
      out.write("/list.bo?category=10&currentPage=1\">자유게시판</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print( contextPath );
      out.write("/movieList.me\">영화 정보</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print( contextPath );
      out.write("/list.bo?category=20&currentPage=1\">나눔</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"search-box\">\r\n");
      out.write("                <form action=\"");
      out.print( contextPath );
      out.write("/searchListView.bo?currentPage=1;\" method=\"get\">\r\n");
      out.write("              	<input type=\"text\" placeholder=\"Search\" name=\"keyword\">\r\n");
      out.write("                <button type=\"submit\" name=\"currentPage\" value=\"1\"><i class=\"fas fa-search\"></i></button>\r\n");
      out.write("            </form>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"login\">\r\n");
      out.write("           		 <!-- 로그인 전 -->\r\n");
      out.write("            	");
if(loginUser == null){ 
      out.write("\r\n");
      out.write("	                <a href=\"");
      out.print( contextPath );
      out.write("\" data-toggle=\"modal\" data-target=\"#loginForm\">로그인</a> |\r\n");
      out.write("	                <a href=\"");
      out.print( contextPath );
      out.write("/enrollForm.me\">회원가입</a>\r\n");
      out.write("                ");
 } else if(loginUser.getMemberId().equals("admin")) { 
      out.write("\r\n");
      out.write("                	<b>");
      out.print( loginUser.getMemberNick() );
      out.write("님</b><br>\r\n");
      out.write("                	<a href=\"");
      out.print( contextPath );
      out.write("/menu.ad\">관리자페이지</a> | \r\n");
      out.write("					<a href=\"");
      out.print( contextPath );
      out.write("/logout.me\">로그아웃</a>\r\n");
      out.write("                <!-- 로그인 후 -->\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("					<b>");
      out.print( loginUser.getMemberNick() );
      out.write("님</b> 환영합니다. <br>\r\n");
      out.write("					<a href=\"");
      out.print( contextPath );
      out.write("/myPageInfo.me\">마이페이지</a> | \r\n");
      out.write("					<a href=\"");
      out.print( contextPath );
      out.write("/logout.me\">로그아웃</a>\r\n");
      out.write("				");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("<!-- Button to Open the Modal -->\r\n");
      out.write("      <!-- \r\n");
      out.write("        data-toggle=\"modal\" : 부트스트랩에서 제공하는 속성, \r\n");
      out.write("                              모달창을 띄울려면 반드시 필요함\r\n");
      out.write("        data-target=\"#myModal\" : 부트스트랩에서 제공하는 속성, \r\n");
      out.write("                    내가 띄우고자 하는 모달창을 연결해주는 속성\r\n");
      out.write("      -->\r\n");
      out.write("       <!--\r\n");
      out.write("        \r\n");
      out.write("        <button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\"#loginForm\">\r\n");
      out.write("            Open Login Form\r\n");
      out.write("\r\n");
      out.write("        </button>-->\r\n");
      out.write("        \r\n");
      out.write("        <!-- The Modal -->\r\n");
      out.write("        <div class=\"modal\" id=\"loginForm\" style=\"margin-top: 10%; \">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" style=\"margin-right: 217px;\r\n");
      out.write("                margin-bottom:20px; border-style: none; font-size: 450%; \">&times;</button>\r\n");
      out.write("            <div class=\"modal-content\"  style=\"border-radius: 30px;\">\r\n");
      out.write("        \r\n");
      out.write("                <!-- Modal Header -->\r\n");
      out.write("              \r\n");
      out.write("                <div class=\"modal-header\" style=\"background-color: rgb(240,240,240); border-radius: 30px 30px 0px 0px;\">\r\n");
      out.write("                <h4 class=\"modal-title\" style=\"margin-left: 200px;\">로그인</h4>\r\n");
      out.write("                \r\n");
      out.write("                </div>\r\n");
      out.write("        \r\n");
      out.write("                <!-- Modal body -->\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                \r\n");
      out.write("                    <form action=\"");
      out.print( contextPath );
      out.write("/login.me\" method=\"post\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          \r\n");
      out.write("                          <input type=\"text\" class=\"form-control\" placeholder=\"아이디\" \r\n");
      out.write("                                        id=\"memberId\" name=\"memberId\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          \r\n");
      out.write("                          <input type=\"password\" class=\"form-control\" placeholder=\"비밀번호\" \r\n");
      out.write("                                        id=\"pwd\" name=\"memberPwd\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group form-check\">\r\n");
      out.write("\r\n");
      out.write("                            <input type=\"checkbox\" id=\"saveId\"\r\n");
      out.write("                            name=\"saveId\" value=\"y\">\r\n");
      out.write("                            <label for=\"saveId\">\r\n");
      out.write("                                아이디 저장\r\n");
      out.write("                            </label>\r\n");
      out.write("\r\n");
      out.write("                          \r\n");
      out.write("                           <a href=\"");
      out.print( contextPath );
      out.write("/memberFindAccount.me\" style=\"color : black; float: right;\">ID/PW찾기</a>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div id=\"footerLogin\"  style=\"margin-left: 75px;\">\r\n");
      out.write("                            <button type=\"button\" id=\"login\" class=\"btn btn-light\" style=\"margin-right: 10px;\" onclick=\"location.href='");
      out.print( contextPath );
      out.write("/enrollForm.me'\">회원가입</button>\r\n");
      out.write("                            <button type=\"submit\" id=\"loginUser\" class=\"btn btn-primary btn-block\" style=\"margin-left: 10px;\">로그인</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </form> \r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("        \r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");

		// session 에 담겨있는 loginUser 값을 뽑기
		// System.out.println(loginUser);
		int memberNo		=  loginUser.getMemberNo();
		String memberId 	=  loginUser.getMemberId();
		String memberName 	=  loginUser.getMemberName();
		String memberNick 	= (loginUser.getMemberNick() == null) 	? "" : loginUser.getMemberNick();
		String email 		= (loginUser.getEmail() == null) 	? "" : loginUser.getEmail();
		String enrollDate 	= (loginUser.getEnrollDate() == null) 	? "" : loginUser.getEnrollDate().toString();
		String memberImg 	= (loginUser.getMemberImg() == null) ? "/resources/images/pngwing.com.png" : loginUser.getMemberImg();
		
		// 삼항연산자 이용 : DB에 없는 값을 불러오면 null 을 불러오므로
		// null 일 경우는 "" (빈 문자열) 로 대체
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"wrapBody\">\r\n");
      out.write("	<div class=\"body\">\r\n");
      out.write("		<div class=\"body_1\">\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>MyPage</title>\r\n");
      out.write(" 	<style>\r\n");
      out.write("        #myMenu a { \r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: black;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"myMenu\">\r\n");
      out.write("        <br><br><br>\r\n");
      out.write("        <div align=\"center\"><img src=\"");
      out.print( contextPath + memberImg );
      out.write("\" height=\"150px\"></div>\r\n");
      out.write("        <br>\r\n");
      out.write("        <div align=\"center\"><h4>");
      out.print( memberNick );
      out.write(" 님</h4></div>\r\n");
      out.write("        <br><br><br>\r\n");
      out.write("        <div align=\"center\"><h4><a href=\"");
      out.print( contextPath );
      out.write("/myPageInfo.me\">내 정보 수정</a></h4></div>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <div align=\"center\"><h4><a href=\"");
      out.print( contextPath );
      out.write("/myPageBoard.me?currentPage=1\">내가 쓴 게시글 조회</a></h4></div>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <div align=\"center\"><h4><a href=\"");
      out.print( contextPath );
      out.write("/myPageReply.me?currentPage=1\">내가 쓴 댓글 조회</a></h4></div>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <div align=\"center\"><h4><a href=\"");
      out.print( contextPath );
      out.write("/myPageCommend.me?currentPage=1\">추천한 게시글 조회</a></h4></div>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <div align=\"center\"><h4><a href=\"");
      out.print( contextPath );
      out.write("/list.mes\">쪽지함</a></h4></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"body_2\">\r\n");
      out.write("	<div class=\"outer\">\r\n");
      out.write("       <br>\r\n");
      out.write("       <h2 align=\"center\">마이페이지</h2>\r\n");
      out.write("       <br>\r\n");
      out.write("       \r\n");
      out.write("       <form id=\"mypage-form\" action=\"");
      out.print( contextPath );
      out.write("/update.me\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("           <input type=\"hidden\" name=\"memberNo\" value=\"");
      out.print( memberNo );
      out.write("\">\r\n");
      out.write("           <!--\r\n");
      out.write("               마이페이지에서 보여져야 하는 것들\r\n");
      out.write("               아이디, 이름, 닉네임, 이메일, 회원가입일\r\n");
      out.write("           -->\r\n");
      out.write("\r\n");
      out.write("           <table>\r\n");
      out.write("               <tr>\r\n");
      out.write("                   <td>&nbsp;&nbsp;아이디</td>\r\n");
      out.write("                   <td colspan=\"2\">\r\n");
      out.write("                       <input type=\"text\" name=\"memberId\" maxlength=\"12\" readonly value=\"");
      out.print( memberId );
      out.write("\">\r\n");
      out.write("                       <!-- 수정을 막기 위해 readonly 부여 -->\r\n");
      out.write("                   </td>\r\n");
      out.write("                   <td></td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                   <td>&nbsp;&nbsp;이름</td>\r\n");
      out.write("                   <td colspan=\"2\">\r\n");
      out.write("                       <input type=\"text\" name=\"memberName\" maxlength=\"6\" required value=\"");
      out.print( memberName );
      out.write("\">\r\n");
      out.write("                   </td>\r\n");
      out.write("                   <td></td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                   <td>&nbsp;&nbsp;닉네임</td>\r\n");
      out.write("                   <td colspan=\"2\">\r\n");
      out.write("                       <input type=\"tel\" name=\"memberNick\" required value=\"");
      out.print( memberNick );
      out.write("\">\r\n");
      out.write("                   </td>\r\n");
      out.write("                   <td>\r\n");
      out.write("                       <input type=\"button\" class=\"btn btn-secondary btn-sm\" value=\"중복확인\">\r\n");
      out.write("                   </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                   <td>&nbsp;&nbsp;이메일</td>\r\n");
      out.write("                   <td colspan=\"2\">\r\n");
      out.write("                       <input type=\"email\" name=\"email\" required value=\"");
      out.print( email );
      out.write("\">\r\n");
      out.write("                   </td>\r\n");
      out.write("                   <td></td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                   <td>&nbsp;&nbsp;회원가입일</td>\r\n");
      out.write("                   <td colspan=\"2\">\r\n");
      out.write("                       <input type=\"text\" name=\"enrollDate\" value=\"");
      out.print( enrollDate );
      out.write("\" readonly>\r\n");
      out.write("                   </td>\r\n");
      out.write("                   <td></td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                   <td colspan=\"4\"><br></td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                   <td rowspan=\"2\" colspan=\"2\" align=\"right\">\r\n");
      out.write("                       <img src=\"");
      out.print( contextPath );
      out.print( memberImg );
      out.write("\" alt=\"\" height=\"100px\" id=\"preview\">\r\n");
      out.write("                       <input type=\"hidden\" name=\"memberImg\" value=\"");
      out.print( memberImg );
      out.write("\">\r\n");
      out.write("                   </td>\r\n");
      out.write("                   <td colspan=\"2\" align=\"center\">\r\n");
      out.write("                       프로필 이미지 변경\r\n");
      out.write("                   </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                   <td colspan=\"2\" align=\"center\">\r\n");
      out.write("                       <input type=\"file\" name=\"updateImg\" class=\"btn btn-secondary btn-sm\" value=\"업로드\" onchange=\"readURL(this);\">\r\n");
      out.write("                   </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("           </table>\r\n");
      out.write("\r\n");
      out.write("           <br><br>\r\n");
      out.write("\r\n");
      out.write("           <div align=\"center\">\r\n");
      out.write("               <button type=\"submit\" class=\"btn btn-secondary btn-sm\">정보변경</button>\r\n");
      out.write("               <button type=\"button\" class=\"btn btn-warning btn-sm\" data-toggle=\"modal\" data-target=\"#updatePwdForm\">비밀번호변경</button>\r\n");
      out.write("           </div>\r\n");
      out.write("\r\n");
      out.write("           <br><br><br><br>\r\n");
      out.write("\r\n");
      out.write("           <div align=\"center\">\r\n");
      out.write("               <button type=\"button\" class=\"btn btn-danger btn-sm\" data-toggle=\"modal\" data-target=\"#deleteForm\">회원탈퇴</button>\r\n");
      out.write("           </div>\r\n");
      out.write("\r\n");
      out.write("           <br><br>\r\n");
      out.write("\r\n");
      out.write("       </form>\r\n");
      out.write("   	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function readURL(input) {\r\n");
      out.write("		  if (input.files && input.files[0]) {\r\n");
      out.write("		    var reader = new FileReader();\r\n");
      out.write("		    reader.onload = function(e) {\r\n");
      out.write("		      document.getElementById('preview').src = e.target.result;\r\n");
      out.write("		    };\r\n");
      out.write("		    reader.readAsDataURL(input.files[0]);\r\n");
      out.write("		  } else {\r\n");
      out.write("		    document.getElementById('preview').src = \"\";\r\n");
      out.write("		  }\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<!-- 필요한 모달창 -->\r\n");
      out.write("	<!-- 비밀번호 변경용 모달창 -->\r\n");
      out.write("	<div class=\"modal\" id=\"updatePwdForm\">\r\n");
      out.write("	       <div class=\"modal-dialog\">\r\n");
      out.write("	         <div class=\"modal-content\">\r\n");
      out.write("	     \r\n");
      out.write("	           <!-- Modal Header -->\r\n");
      out.write("	          <div class=\"modal-header\">\r\n");
      out.write("	            <h4 class=\"modal-title\">비밀번호 변경</h4>\r\n");
      out.write("	            <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("	          </div>\r\n");
      out.write("	    \r\n");
      out.write("	          <!-- Modal body -->\r\n");
      out.write("	          <div class=\"modal-body\">\r\n");
      out.write("	            <form action=\"");
      out.print( contextPath );
      out.write("/updatePwd.me\" method=\"post\">\r\n");
      out.write("	                \r\n");
      out.write("	                <!-- \r\n");
      out.write("	                    비밀번호 변경 시 : 현재 비밀번호, 변경할 비밀번호, 변경할 비밀번호 확인\r\n");
      out.write("	                                         , 변경할 아이디\r\n");
      out.write("	                 -->\r\n");
      out.write("	                 <!--  \r\n");
      out.write("	                     비밀번호 변경 요청 시 변경하고자 하는 회원의 아이디값도 같이 form 으로 넘기고자 함\r\n");
      out.write("	                     input type=\"text\" 로 아이디를 굳이 입력받지 않고도 넘기고 싶음\r\n");
      out.write("	                     => input type=\"hidden\" 로 아이디값을 넘길 것\r\n");
      out.write("	                 -->\r\n");
      out.write("	                 <input type=\"hidden\" name=\"memberId\" value=\"");
      out.print( memberId );
      out.write("\">\r\n");
      out.write("	                 \r\n");
      out.write("	                <table>\r\n");
      out.write("	                    <tr>\r\n");
      out.write("	                        <td>현재 비밀번호</td>\r\n");
      out.write("	                        <td>\r\n");
      out.write("	                            <input type=\"password\" name=\"memberPwd\" required>\r\n");
      out.write("	                        </td>\r\n");
      out.write("	                    </tr>\r\n");
      out.write("	                    <tr>\r\n");
      out.write("	                        <td>변경할 비밀번호</td>\r\n");
      out.write("	                        <td>\r\n");
      out.write("	                        	<input type=\"password\" name=\"updatePwd\" required>\r\n");
      out.write("	                        </td>\r\n");
      out.write("	                    </tr>\r\n");
      out.write("	                    <tr>\r\n");
      out.write("	                        <td>변경할 비밀번호 재입력</td>\r\n");
      out.write("	                        <td>\r\n");
      out.write("	                            <input type=\"password\" name=\"checkPwd\" required>\r\n");
      out.write("	                        </td>\r\n");
      out.write("	                    </tr>\r\n");
      out.write("	                </table>\r\n");
      out.write("	                <br>\r\n");
      out.write("	                <button type=\"submit\" class=\"btn btn-secondary btn-sm\" onclick=\"return validatePwd();\">비밀번호 변경</button>\r\n");
      out.write("	            </form>\r\n");
      out.write("	            \r\n");
      out.write("	            <script>\r\n");
      out.write("	                function validatePwd() {\r\n");
      out.write("	                    \r\n");
      out.write("	                    // 변경할 비번 == 변경할 비번 확인 : return true;\r\n");
      out.write("	                    // 변경할 비번 != 변경할 비번 확인 : return false;\r\n");
      out.write("	                    if($(\"input[name=updatePwd]\").val() != $(\"input[name=checkPwd]\").val()) {\r\n");
      out.write("	                        alert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("	                        return false;\r\n");
      out.write("	                    }\r\n");
      out.write("	                    return true;\r\n");
      out.write("	                }\r\n");
      out.write("	            </script>\r\n");
      out.write("	            \r\n");
      out.write("	          </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	    \r\n");
      out.write("	    <!-- 회원 탈퇴용 모달창 -->\r\n");
      out.write("	    <div class=\"modal\" id=\"deleteForm\">\r\n");
      out.write("	      <div class=\"modal-dialog\">\r\n");
      out.write("	        <div class=\"modal-content\">\r\n");
      out.write("	    \r\n");
      out.write("	          <!-- Modal Header -->\r\n");
      out.write("	          <div class=\"modal-header\">\r\n");
      out.write("	            <h4 class=\"modal-title\">회원탈퇴</h4>\r\n");
      out.write("	            <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("	          </div>\r\n");
      out.write("	    \r\n");
      out.write("	          <!-- Modal body -->\r\n");
      out.write("	          <div class=\"modal-body\">\r\n");
      out.write("	            <b>\r\n");
      out.write("	                탈퇴 후 복구가 불가능합니다. <br>\r\n");
      out.write("	                정말로 탈퇴하시겠습니까? <br><br>\r\n");
      out.write("	            </b>\r\n");
      out.write("	            \r\n");
      out.write("	            <form action=\"");
      out.print( contextPath );
      out.write("/delete.me\" method=\"post\">\r\n");
      out.write("	                <!-- 탈퇴 시 : 비밀번호 확인 -->\r\n");
      out.write("	                <table>\r\n");
      out.write("	                    <tr>\r\n");
      out.write("	                        <td>비밀번호</td>\r\n");
      out.write("	                        <td>\r\n");
      out.write("	                            <input type=\"password\" name=\"memberPwd\" required>\r\n");
      out.write("	                        </td>\r\n");
      out.write("	                </table>\r\n");
      out.write("	                <br>\r\n");
      out.write("	                <button type=\"submit\" class=\"btn btn-secondary btn-sm\">탈퇴하기</button>\r\n");
      out.write("	                \r\n");
      out.write("	            </form>\r\n");
      out.write("	          </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	    \r\n");
      out.write("	    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>LMC</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("\r\n");
      out.write("    .wrap {\r\n");
      out.write("        background-color: white;\r\n");
      out.write("        width: 1200px;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    footer {\r\n");
      out.write("        background-color: rgb(44, 44, 44);\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        font-family: 'LINESeedKR-Bd';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    footer p {\r\n");
      out.write("        font-size: 15px;\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer_text a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: white;\r\n");
      out.write("        padding: 5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer_logo img {\r\n");
      out.write("        width: 120px;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("        \r\n");
      out.write("        <footer>\r\n");
      out.write("            <div class=\"footer_logo\">\r\n");
      out.write("                <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/Logo_w.png\" alt=\"로고\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <p>© 2023. LMC. all rights reserved.</p>\r\n");
      out.write("            <div class=\"footer_text\">\r\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/list.no?currentPage=1\">공지사항</a>\r\n");
      out.write("                <a href=\"\">개인정보취급방침</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
